### ISSUE TITLE
typo/mistake in csp_whitelist.xml

### ISSUE THREAD

**Issue by live4soccer7** [basantmandal/HK2-CSP#1]
I believe this line should be changed: 
<csp_whitelist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Csp/etc/csp_whitelist.xsd">

to: 
<csp_whitelist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Csp:etc/csp_whitelist.xsd">

**Comment by basantmandal** [comment]
Hi @live4soccer7 

Thank you for reporting. I have fixed and updated everywhere.

Commit - [https://github.com/basantmandal/HK2-CSP/commit/683133d18178fb411348fa5a667c863f4002158c](url)

Thanks a lot for improving this free Magento Module.

**Comment by live4soccer7** [comment]
> Hi @live4soccer7
> 
> Thank you for reporting. I have fixed and updated everywhere.
> 
> Commit - [https://github.com/basantmandal/HK2-CSP/commit/683133d18178fb411348fa5a667c863f4002158c](url)
> 
> Thanks a lot for improving this free Magento Module.

You are very welcome :)
